export const SET_DATA_API = "SET_DATA_API";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const SET_CURRENT_EXERCISE = "SET_CURRENT_EXERCISE";
export const GET_CURRENT_EXERCISE = "GET_CURENT_EXERCISE";
